library("neldermead")
library("fBasics")
library("gsl")
library("stabledist")
library("statmod")
source("/Users/Ian/Google.Drive/R.Analyses/pulsR/levy_pruning_cf.r")
source("/Users/Ian/Google.Drive/R.Analyses/pulsR/levy_pruning_tools.r")
source("/Users/Ian/Google.Drive/R.Analyses/pulsR/levy_pruning_prob.r")
source("/Users/Ian/Google.Drive/R.Analyses/pulsR/levy_pruning_optim.r")
source("/Users/Ian/Google.Drive/R.Analyses/pulsR/levy_pruning_sim.r")
# to source each script, you have to provide the path to their dependent source scripts (open each file and check)
